In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Stock data
import yfinance as yf

## Download 5 Years of Stock Data

In [2]:
# Indian Large Cap Stocks

tickers = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS"
]

In [3]:
# Download historical data

data = yf.download(

    tickers,

    start="2019-01-01",

    end="2024-12-31",

    auto_adjust=True,

    group_by="ticker"
)

# Display first rows

data.head()

[*********************100%***********************]  5 of 5 completed

Ticker     RELIANCE.NS                                                \
Price             Open        High         Low       Close    Volume
Date
2019-01-01  498.077624  498.985034  491.371654  496.196381   9746670
2019-01-02  493.319235  498.852220  487.343625  489.733887  15628818
2019-01-03  490.220755  493.363478  482.518879  483.691864  16288287
2019-01-04  485.750155  488.870748  478.535167  486.303436  18516544
2019-01-07  489.999414  495.067613  487.343578  489.003479  12060290

Ticker     HDFCBANK.NS                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2019-01-01  491.462098  496.855695  486.368852  496.185852   6373440  ...
2019-01-02  494.961652  496.047285  489.625800  491.658508   8134232  ...
2019-01-03  490.665257  491.600771  485.768317  487.801025  12771664  ...
2019-01-04  488.597947  491.658541  487.466127  489.106110   7287120  ...
2019-01-07  491.473663  493.240757  489.233088  489.845184   5387012  ...

Ticker           TCS.NS                                                  \
Price              Open         High          Low        Close   Volume
Date
2019-01-01  1555.421809  1566.906991  1546.397737  1561.000366  1094883
2019-01-02  1562.805421  1586.965286  1558.703569  1577.818237  2100463
2019-01-03  1574.290569  1595.579138  1553.042959  1558.662476  2611668
2019-01-04  1558.703259  1559.687663  1510.301421  1539.711670  4280862
2019-01-07  1551.976353  1565.922646  1543.116315  1556.980591  1856423

Ticker         INFY.NS
Price             Open        High         Low       Close   Volume
Date
2019-01-01  538.386137  542.744035  532.847111  541.725830  2943390
2019-01-02  542.499538  549.016049  539.282001  544.983948  7416655
2019-01-03  547.387039  551.459860  540.137400  545.065552  6827249
2019-01-04  547.183436  548.934769  530.281231  538.467590  7889310
2019-01-07  541.684990  548.690220  538.834016  547.142578  8046340

[5 rows x 25 columns]

## Save Raw Dataset

In [7]:
# Save raw stock data

data.to_csv("./data/raw_stock_data.csv")

print("Dataset saved successfully.")

Dataset saved successfully.

In [8]:
# Dataset shape

print("Shape :", data.shape)

print()

# Column names

print(data.columns)

print()

# First five rows

data.head()

Shape : (1480, 25)

MultiIndex([( 'RELIANCE.NS',   'Open'),
            ( 'RELIANCE.NS',   'High'),
            ( 'RELIANCE.NS',    'Low'),
            ( 'RELIANCE.NS',  'Close'),
            ( 'RELIANCE.NS', 'Volume'),
            ( 'HDFCBANK.NS',   'Open'),
            ( 'HDFCBANK.NS',   'High'),
            ( 'HDFCBANK.NS',    'Low'),
            ( 'HDFCBANK.NS',  'Close'),
            ( 'HDFCBANK.NS', 'Volume'),
            ('ICICIBANK.NS',   'Open'),
            ('ICICIBANK.NS',   'High'),
            ('ICICIBANK.NS',    'Low'),
            ('ICICIBANK.NS',  'Close'),
            ('ICICIBANK.NS', 'Volume'),
            (      'TCS.NS',   'Open'),
            (      'TCS.NS',   'High'),
            (      'TCS.NS',    'Low'),
            (      'TCS.NS',  'Close'),
            (      'TCS.NS', 'Volume'),
            (     'INFY.NS',   'Open'),
            (     'INFY.NS',   'High'),
            (     'INFY.NS',    'Low'),
            (     'INFY.NS',  'Close'),
            (     'INFY.NS', 'Volume')],
           names=['Ticker', 'Price'])

Ticker     RELIANCE.NS                                                \
Price             Open        High         Low       Close    Volume
Date
2019-01-01  498.077624  498.985034  491.371654  496.196381   9746670
2019-01-02  493.319235  498.852220  487.343625  489.733887  15628818
2019-01-03  490.220755  493.363478  482.518879  483.691864  16288287
2019-01-04  485.750155  488.870748  478.535167  486.303436  18516544
2019-01-07  489.999414  495.067613  487.343578  489.003479  12060290

Ticker     HDFCBANK.NS                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2019-01-01  491.462098  496.855695  486.368852  496.185852   6373440  ...
2019-01-02  494.961652  496.047285  489.625800  491.658508   8134232  ...
2019-01-03  490.665257  491.600771  485.768317  487.801025  12771664  ...
2019-01-04  488.597947  491.658541  487.466127  489.106110   7287120  ...
2019-01-07  491.473663  493.240757  489.233088  489.845184   5387012  ...

Ticker           TCS.NS                                                  \
Price              Open         High          Low        Close   Volume
Date
2019-01-01  1555.421809  1566.906991  1546.397737  1561.000366  1094883
2019-01-02  1562.805421  1586.965286  1558.703569  1577.818237  2100463
2019-01-03  1574.290569  1595.579138  1553.042959  1558.662476  2611668
2019-01-04  1558.703259  1559.687663  1510.301421  1539.711670  4280862
2019-01-07  1551.976353  1565.922646  1543.116315  1556.980591  1856423

Ticker         INFY.NS
Price             Open        High         Low       Close   Volume
Date
2019-01-01  538.386137  542.744035  532.847111  541.725830  2943390
2019-01-02  542.499538  549.016049  539.282001  544.983948  7416655
2019-01-03  547.387039  551.459860  540.137400  545.065552  6827249
2019-01-04  547.183436  548.934769  530.281231  538.467590  7889310
2019-01-07  541.684990  548.690220  538.834016  547.142578  8046340

[5 rows x 25 columns]

In [9]:
# Import reusable functions

from src.data import download_stock_data
from src.data import save_data

In [10]:
# Download data

stocks = download_stock_data(

    tickers,

    "2019-01-01",

    "2024-12-31"
)

stocks.head()

[*********************100%***********************]  5 of 5 completed

Ticker     ICICIBANK.NS                                                \
Price              Open        High         Low       Close    Volume
Date
2019-01-01   348.786163  351.970091  343.865522  350.957031   7759872
2019-01-02   348.786150  354.961058  347.628342  351.777130  18243156
2019-01-03   352.163093  354.382191  349.316832  350.474640  12884409
2019-01-04   349.123861  355.829414  345.457488  352.356049  22896026
2019-01-07   354.575150  357.952056  353.658549  354.768127  12719847

Ticker     RELIANCE.NS                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2019-01-01  498.077624  498.985034  491.371654  496.196381   9746670  ...
2019-01-02  493.319235  498.852220  487.343625  489.733887  15628818  ...
2019-01-03  490.220755  493.363478  482.518879  483.691864  16288287  ...
2019-01-04  485.750155  488.870748  478.535167  486.303436  18516544  ...
2019-01-07  489.999414  495.067613  487.343578  489.003479  12060290  ...

Ticker           TCS.NS                                                  \
Price              Open         High          Low        Close   Volume
Date
2019-01-01  1555.421809  1566.906991  1546.397737  1561.000366  1094883
2019-01-02  1562.805421  1586.965286  1558.703569  1577.818237  2100463
2019-01-03  1574.290569  1595.579138  1553.042959  1558.662476  2611668
2019-01-04  1558.703259  1559.687663  1510.301421  1539.711670  4280862
2019-01-07  1551.976353  1565.922646  1543.116315  1556.980591  1856423

Ticker         INFY.NS
Price             Open        High         Low       Close   Volume
Date
2019-01-01  538.386137  542.744035  532.847111  541.725830  2943390
2019-01-02  542.499538  549.016049  539.282001  544.983948  7416655
2019-01-03  547.387039  551.459860  540.137400  545.065552  6827249
2019-01-04  547.183436  548.934769  530.281231  538.467590  7889310
2019-01-07  541.684990  548.690220  538.834016  547.142578  8046340

[5 rows x 25 columns]

In [11]:
# Save data

save_data(

    stocks,

    "./data/raw_stock_data.csv"
)

Dataset saved successfully.