In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Stock data
import yfinance as yf

## Download 5 Years of Stock Data

In [2]:
# Indian Large Cap Stocks

tickers = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS"
]

In [3]:
# Download historical data

data = yf.download(

    tickers,

    start="2019-01-01",

    end="2024-12-31",

    auto_adjust=True,

    group_by="ticker"
)

# Display first rows

data.head()

[*********************100%***********************]  5 of 5 completed

Ticker     ICICIBANK.NS                                                \
Price              Open        High         Low       Close    Volume
Date
2019-01-01   348.786133  351.970061  343.865493  350.957001   7759872
2019-01-02   348.786150  354.961058  347.628342  351.777130  18243156
2019-01-03   352.163062  354.382160  349.316801  350.474609  12884409
2019-01-04   349.123891  355.829445  345.457518  352.356079  22896026
2019-01-07   354.575119  357.952025  353.658519  354.768097  12719847

Ticker     RELIANCE.NS                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2019-01-01  498.077593  498.985004  491.371623  496.196350   9746670  ...
2019-01-02  493.319266  498.852251  487.343655  489.733917  15628818  ...
2019-01-03  490.220816  493.363540  482.518940  483.691925  16288287  ...
2019-01-04  485.750186  488.870779  478.535197  486.303467  18516544  ...
2019-01-07  489.999475  495.067675  487.343638  489.003540  12060290  ...

Ticker     HDFCBANK.NS                                                \
Price             Open        High         Low       Close    Volume
Date
2019-01-01  491.462128  496.855726  486.368882  496.185883   6373440
2019-01-02  494.961590  496.047224  489.625740  491.658447   8134232
2019-01-03  490.665196  491.600710  485.768257  487.800964  12771664
2019-01-04  488.597855  491.658449  487.466035  489.106018   7287120
2019-01-07  491.473632  493.240726  489.233058  489.845154   5387012

Ticker           TCS.NS
Price              Open         High          Low        Close   Volume
Date
2019-01-01  1555.421931  1566.907114  1546.397858  1561.000488  1094883
2019-01-02  1562.805058  1586.964918  1558.703207  1577.817871  2100463
2019-01-03  1574.290569  1595.579138  1553.042959  1558.662476  2611668
2019-01-04  1558.703259  1559.687663  1510.301421  1539.711670  4280862
2019-01-07  1551.976353  1565.922646  1543.116315  1556.980591  1856423

[5 rows x 25 columns]

## Save Raw Dataset

In [5]:
# Save raw stock data

data.to_csv("../data/raw_stock_data.csv")

print("Dataset saved successfully.")

Dataset saved successfully.

In [6]:
# Dataset shape

print("Shape :", data.shape)

print()

# Column names

print(data.columns)

print()

# First five rows

data.head()

Shape : (1480, 25)

MultiIndex([('ICICIBANK.NS',   'Open'),
            ('ICICIBANK.NS',   'High'),
            ('ICICIBANK.NS',    'Low'),
            ('ICICIBANK.NS',  'Close'),
            ('ICICIBANK.NS', 'Volume'),
            ( 'RELIANCE.NS',   'Open'),
            ( 'RELIANCE.NS',   'High'),
            ( 'RELIANCE.NS',    'Low'),
            ( 'RELIANCE.NS',  'Close'),
            ( 'RELIANCE.NS', 'Volume'),
            (     'INFY.NS',   'Open'),
            (     'INFY.NS',   'High'),
            (     'INFY.NS',    'Low'),
            (     'INFY.NS',  'Close'),
            (     'INFY.NS', 'Volume'),
            ( 'HDFCBANK.NS',   'Open'),
            ( 'HDFCBANK.NS',   'High'),
            ( 'HDFCBANK.NS',    'Low'),
            ( 'HDFCBANK.NS',  'Close'),
            ( 'HDFCBANK.NS', 'Volume'),
            (      'TCS.NS',   'Open'),
            (      'TCS.NS',   'High'),
            (      'TCS.NS',    'Low'),
            (      'TCS.NS',  'Close'),
            (      'TCS.NS', 'Volume')],
           names=['Ticker', 'Price'])

Ticker     ICICIBANK.NS                                                \
Price              Open        High         Low       Close    Volume
Date
2019-01-01   348.786133  351.970061  343.865493  350.957001   7759872
2019-01-02   348.786150  354.961058  347.628342  351.777130  18243156
2019-01-03   352.163062  354.382160  349.316801  350.474609  12884409
2019-01-04   349.123891  355.829445  345.457518  352.356079  22896026
2019-01-07   354.575119  357.952025  353.658519  354.768097  12719847

Ticker     RELIANCE.NS                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2019-01-01  498.077593  498.985004  491.371623  496.196350   9746670  ...
2019-01-02  493.319266  498.852251  487.343655  489.733917  15628818  ...
2019-01-03  490.220816  493.363540  482.518940  483.691925  16288287  ...
2019-01-04  485.750186  488.870779  478.535197  486.303467  18516544  ...
2019-01-07  489.999475  495.067675  487.343638  489.003540  12060290  ...

Ticker     HDFCBANK.NS                                                \
Price             Open        High         Low       Close    Volume
Date
2019-01-01  491.462128  496.855726  486.368882  496.185883   6373440
2019-01-02  494.961590  496.047224  489.625740  491.658447   8134232
2019-01-03  490.665196  491.600710  485.768257  487.800964  12771664
2019-01-04  488.597855  491.658449  487.466035  489.106018   7287120
2019-01-07  491.473632  493.240726  489.233058  489.845154   5387012

Ticker           TCS.NS
Price              Open         High          Low        Close   Volume
Date
2019-01-01  1555.421931  1566.907114  1546.397858  1561.000488  1094883
2019-01-02  1562.805058  1586.964918  1558.703207  1577.817871  2100463
2019-01-03  1574.290569  1595.579138  1553.042959  1558.662476  2611668
2019-01-04  1558.703259  1559.687663  1510.301421  1539.711670  4280862
2019-01-07  1551.976353  1565.922646  1543.116315  1556.980591  1856423

[5 rows x 25 columns]

In [ ]:
# Import reusable functions

from src.data import download_stock_data
from src.data import save_data

ModuleNotFoundError: No module named 'Indian_Equities_Analytics'