In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Day04/stocks_raw.csv")

df.head()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2
0,NaN,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,NaN,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS
1,2024-06-05,1403.821044921875,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-06,1414.5416259765625,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-07,1452.4345703125,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-10,1453.867431640625,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(df.columns)

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Stock', 'Close.1',
       'High.1', 'Low.1', 'Open.1', 'Volume.1', 'Close.2', 'High.2', 'Low.2',
       'Open.2', 'Volume.2'],
      dtype='object')

In [4]:
df["Date"] = pd.to_datetime(df["Date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1494 non-null   datetime64[ns]
 1   Close     499 non-null    object
 2   High      499 non-null    object
 3   Low       499 non-null    object
 4   Open      499 non-null    object
 5   Volume    499 non-null    object
 6   Stock     1494 non-null   object
 7   Close.1   499 non-null    object
 8   High.1    499 non-null    object
 9   Low.1     499 non-null    object
 10  Open.1    499 non-null    object
 11  Volume.1  499 non-null    object
 12  Close.2   499 non-null    object
 13  High.2    499 non-null    object
 14  Low.2     499 non-null    object
 15  Open.2    499 non-null    object
 16  Volume.2  499 non-null    object
dtypes: datetime64[ns](1), object(16)
memory usage: 198.7+ KB

In [5]:
sector_map = {
    "RELIANCE": "Energy",
    "TCS": "Information Technology",
    "INFY": "Information Technology"
}

df["Sector"] = df["Stock"].map(sector_map)

df.head()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Sector
0,NaT,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,NaN,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,NaN
1,2024-06-05,1403.821044921875,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Energy
2,2024-06-06,1414.5416259765625,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Energy
3,2024-06-07,1452.4345703125,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Energy
4,2024-06-10,1453.867431640625,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Energy

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1494 non-null   datetime64[ns]
 1   Close     499 non-null    object
 2   High      499 non-null    object
 3   Low       499 non-null    object
 4   Open      499 non-null    object
 5   Volume    499 non-null    object
 6   Stock     1494 non-null   object
 7   Close.1   499 non-null    object
 8   High.1    499 non-null    object
 9   Low.1     499 non-null    object
 10  Open.1    499 non-null    object
 11  Volume.1  499 non-null    object
 12  Close.2   499 non-null    object
 13  High.2    499 non-null    object
 14  Low.2     499 non-null    object
 15  Open.2    499 non-null    object
 16  Volume.2  499 non-null    object
 17  Sector    1494 non-null   object
dtypes: datetime64[ns](1), object(17)
memory usage: 210.4+ KB

In [9]:
df["Close"] = pd.to_numeric(df["Close"], errors="coerce")

In [10]:
print(df["Close"].dtype)

float64

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

In [17]:
monthly_avg = (
    df.groupby([
        "Stock",
        pd.Grouper(key="Date", freq="ME")
    ])["Close"]
    .mean()
    .reset_index()
)

monthly_avg.head()

  Stock       Date  Close
0  INFY 2024-06-30    NaN
1  INFY 2024-07-31    NaN
2  INFY 2024-08-31    NaN
3  INFY 2024-09-30    NaN
4  INFY 2024-10-31    NaN

In [18]:
monthly_volatility = (
    df.groupby([
        "Stock",
        pd.Grouper(key="Date", freq="ME")
    ])["Close"]
    .std()
    .reset_index()
)

monthly_volatility.columns = [
    "Stock",
    "Date",
    "Monthly_Volatility"
]

monthly_volatility.head()

  Stock       Date  Monthly_Volatility
0  INFY 2024-06-30                 NaN
1  INFY 2024-07-31                 NaN
2  INFY 2024-08-31                 NaN
3  INFY 2024-09-30                 NaN
4  INFY 2024-10-31                 NaN

In [19]:
quarterly = (
    df.groupby([
        "Stock",
        pd.Grouper(key="Date", freq="QE")
    ])["Close"]
    .mean()
    .reset_index()
)

quarterly.head()

  Stock       Date  Close
0  INFY 2024-06-30    NaN
1  INFY 2024-09-30    NaN
2  INFY 2024-12-31    NaN
3  INFY 2025-03-31    NaN
4  INFY 2025-06-30    NaN

In [20]:
monthly_summary = pd.merge(
    monthly_avg,
    monthly_volatility,
    on=["Stock", "Date"]
)

monthly_summary.to_csv(
    "monthly_summary.csv",
    index=False
)

print("File Saved Successfully")

File Saved Successfully