# Week 4 - Day 1

# Descriptive Statistics of Stock Returns

## Objective

Analyze daily returns of five Indian stocks using descriptive statistics.

Statistics computed:

- Mean
- Median
- Mode
- Variance
- Standard Deviation
- Skewness
- Kurtosis

In [29]:
import pandas as pd
import numpy as np
import yfinance as yf

In [30]:
stocks = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS"
]

In [31]:
data = yf.download(
    stocks,
    period="5y",
    auto_adjust=True
)

[*********************100%***********************]  5 of 5 completed

In [32]:
close_prices = data["Close"]

close_prices.head()

Ticker      HDFCBANK.NS  ICICIBANK.NS      INFY.NS  RELIANCE.NS       TCS.NS
Date
2021-06-15   705.764221    624.126160  1283.726440  1019.065308  2843.680176
2021-06-16   703.088501    619.096741  1289.561646  1001.673218  2853.790771
2021-06-17   694.327087    612.229675  1302.365356  1003.507507  2891.616455
2021-06-18   700.815308    609.715088  1309.332886  1008.036682  2873.792969
2021-06-21   705.030212    610.537231  1306.720093  1013.290588  2852.701416

In [33]:
returns = close_prices.pct_change().dropna()

returns.head()

Ticker      HDFCBANK.NS  ICICIBANK.NS   INFY.NS  RELIANCE.NS    TCS.NS
Date
2021-06-16    -0.003791     -0.008058  0.004546    -0.017067  0.003555
2021-06-17    -0.012461     -0.011092  0.009929     0.001831  0.013255
2021-06-18     0.009345     -0.004107  0.005350     0.004513 -0.006164
2021-06-21     0.006014      0.001348 -0.001996     0.005212 -0.007339
2021-06-22    -0.003291     -0.000634  0.007698    -0.005140  0.008585

## Daily Returns

Daily returns are calculated using percentage change in closing prices.

In [34]:
summary = []

In [35]:
for stock in returns.columns:

    r = returns[stock]

    summary.append({
        "Stock": stock,
        "Mean": r.mean(),
        "Median": r.median(),
        "Mode": r.mode().iloc[0],
        "Variance": r.var(),
        "Std_Dev": r.std(),
        "Skewness": r.skew(),
        "Kurtosis": r.kurt()
    })

In [36]:
summary_df = pd.DataFrame(summary)

summary_df

,Stock,Mean,Median,Mode,Variance,Std_Dev,Skewness,Kurtosis
0,HDFCBANK.NS,0.000164,0.000303,0.0,0.000171,0.013091,-0.064035,5.762432
1,ICICIBANK.NS,0.000692,0.000347,0.0,0.000164,0.012818,0.342408,5.987205
2,INFY.NS,0.000025,0.000000,0.0,0.000249,0.015775,-0.236451,3.860705
3,RELIANCE.NS,0.000300,0.000313,0.0,0.000198,0.014070,0.089196,2.689979
4,TCS.NS,-0.000128,-0.000312,0.0,0.000187,0.013674,-0.161720,3.945458

In [37]:
summary_df = summary_df.round(4)

summary_df

          Stock    Mean  Median  Mode  Variance  Std_Dev  Skewness  Kurtosis
0   HDFCBANK.NS  0.0002  0.0003   0.0    0.0002   0.0131   -0.0640    5.7624
1  ICICIBANK.NS  0.0007  0.0003   0.0    0.0002   0.0128    0.3424    5.9872
2       INFY.NS  0.0000  0.0000   0.0    0.0002   0.0158   -0.2365    3.8607
3   RELIANCE.NS  0.0003  0.0003   0.0    0.0002   0.0141    0.0892    2.6900
4        TCS.NS -0.0001 -0.0003   0.0    0.0002   0.0137   -0.1617    3.9455

In [38]:
summary_df.to_csv(
    "descriptive_statistics.csv",
    index=False
)

# Interpretation of Skewness

## Skewness measures the asymmetry of a distribution.

 Positive Skewness:
  The distribution has a longer right tail. Large positive returns occur occasionally.

 Negative Skewness:
  The distribution has a longer left tail. Large negative returns occur occasionally.

 Near Zero:
  Returns are approximately symmetric.

# Interpretation of Kurtosis

## Kurtosis measures the heaviness of tails.

 High Kurtosis:
  More extreme returns than a normal distribution. Indicates higher risk.

 Low Kurtosis:
  Fewer extreme returns.

 Kurtosis near Zero:
  Similar to a normal distribution.

In [39]:
print(summary_df)

          Stock    Mean  Median  Mode  Variance  Std_Dev  Skewness  Kurtosis
0   HDFCBANK.NS  0.0002  0.0003   0.0    0.0002   0.0131   -0.0640    5.7624
1  ICICIBANK.NS  0.0007  0.0003   0.0    0.0002   0.0128    0.3424    5.9872
2       INFY.NS  0.0000  0.0000   0.0    0.0002   0.0158   -0.2365    3.8607
3   RELIANCE.NS  0.0003  0.0003   0.0    0.0002   0.0141    0.0892    2.6900
4        TCS.NS -0.0001 -0.0003   0.0    0.0002   0.0137   -0.1617    3.9455

# Conclusion

The descriptive statistics provide insights into the return behavior of each stock.

Key observations:

1. Mean return indicates average daily performance.
2. Standard deviation measures volatility and risk.
3. Skewness reveals whether returns are biased toward gains or losses.
4. Kurtosis indicates the likelihood of extreme market movements.

These statistics help investors understand both expected returns and associated risks.