# Week 3 - Day 5

# Candlestick Charts

## Objective

Create a candlestick chart for Reliance stock using the last 3 months of data.

### Features
- Candlestick chart
- 20-Day Moving Average
- 50-Day Moving Average
- Interactive Plotly chart

In [1]:
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go

## Download Last 3 Months Data

Download Reliance stock data using yfinance.

In [2]:
reliance = yf.download(
    "RELIANCE.NS",
    period="3mo",
    auto_adjust=False
)

reliance.head()

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2026-03-12,1385.792603,1392.199951,1410.900024,1381.099976,1390.000000,20939959
2026-03-13,1374.345581,1380.699951,1400.800049,1378.400024,1385.199951,17265090
2026-03-16,1388.679321,1395.099976,1397.300049,1363.500000,1380.000000,22837802
2026-03-17,1391.167725,1397.599976,1405.900024,1388.199951,1399.000000,19007744
2026-03-18,1401.619507,1408.099976,1412.900024,1397.199951,1397.199951,9559327

In [3]:
print(reliance.columns)

MultiIndex([('Adj Close', 'RELIANCE.NS'),
            (    'Close', 'RELIANCE.NS'),
            (     'High', 'RELIANCE.NS'),
            (      'Low', 'RELIANCE.NS'),
            (     'Open', 'RELIANCE.NS'),
            (   'Volume', 'RELIANCE.NS')],
           names=['Price', 'Ticker'])

In [4]:
reliance.columns = reliance.columns.get_level_values(0)

## Calculate Moving Averages

Moving averages help identify market trends.

In [5]:
reliance["MA20"] = (
    reliance["Close"]
    .rolling(20)
    .mean()
)

reliance["MA50"] = (
    reliance["Close"]
    .rolling(50)
    .mean()
)

reliance.head()

Price,Adj Close,Close,High,Low,Open,Volume,MA20,MA50
Date,,,,,,,,
2026-03-12,1385.792603,1392.199951,1410.900024,1381.099976,1390.000000,20939959,NaN,NaN
2026-03-13,1374.345581,1380.699951,1400.800049,1378.400024,1385.199951,17265090,NaN,NaN
2026-03-16,1388.679321,1395.099976,1397.300049,1363.500000,1380.000000,22837802,NaN,NaN
2026-03-17,1391.167725,1397.599976,1405.900024,1388.199951,1399.000000,19007744,NaN,NaN
2026-03-18,1401.619507,1408.099976,1412.900024,1397.199951,1397.199951,9559327,NaN,NaN

In [6]:
fig = go.Figure()

In [7]:
fig.add_trace(
    go.Candlestick(
        x=reliance.index,
        open=reliance["Open"],
        high=reliance["High"],
        low=reliance["Low"],
        close=reliance["Close"],
        name="Reliance"
    )
)

In [8]:
fig.add_trace(
    go.Scatter(
        x=reliance.index,
        y=reliance["MA20"],
        mode="lines",
        name="20-Day MA"
    )
)

In [9]:
fig.add_trace(
    go.Scatter(
        x=reliance.index,
        y=reliance["MA50"],
        mode="lines",
        name="50-Day MA"
    )
)

In [10]:
fig.update_layout(
    title="Reliance Candlestick Chart",
    xaxis_title="Date",
    yaxis_title="Price",
    template="plotly_white",
    xaxis_rangeslider_visible=False
)

In [11]:
fig.show()

In [12]:
fig.write_html(
    "../images/reliance_candlestick.html"
)

## Observations

1. Candlestick charts show daily price movement.
2. Green candles indicate price increase.
3. Red candles indicate price decrease.
4. Moving averages smooth short-term fluctuations.
5. MA20 reacts faster than MA50.