In [31]:
# Numerical computing
import numpy as np

# Data handling
import pandas as pd

# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Time-series split
from sklearn.model_selection import TimeSeriesSplit

# Evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [22]:
# Numerical computing
import numpy as np

# Data handling
import pandas as pd

# Machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Time-series split
from sklearn.model_selection import TimeSeriesSplit

# Evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [32]:
# Load cleaned dataset

data = pd.read_csv(
    "../Day01/ml_dataset.csv",
)

# Display first rows
data.head()

,Price,Close,High,Low,Open,Volume,SMA_10,SMA_20,RSI,MACD,Signal,Return,Lag_1,Lag_5,Lag_21,Target
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-31,628.599609375,647.1238564671794,626.6180767993984,647.0125063572486,34750310,666.229224,674.894650,25.145877,-7.557652,-1.616914,-0.022234,-0.024394,-0.003471,0.017024,-0.018524
3,2020-02-03,616.9551391601562,623.3896651574961,606.9583015760081,610.0085691432375,30712290,659.690070,672.311942,24.072083,-10.665002,-3.426531,-0.018524,-0.022234,-0.009859,0.001205,0.029520
4,2020-02-04,635.167724609375,637.8840014691701,622.4323157911366,623.411935184783,25383901,654.903156,670.125549,34.425487,-11.525141,-5.046253,0.029520,-0.018524,-0.023099,-0.023192,0.015493

In [33]:
# Feature columns

feature_cols = [
    "SMA_20",
    "RSI",
    "MACD",
    "Lag_1",
    "Lag_5",
    "Lag_21"
]

# Feature matrix
X = data[feature_cols]

In [34]:
# Target column

y = data["Target"]

In [35]:
# Combine X and y

dataset = pd.concat([X, y], axis=1)

# Remove missing values

dataset = dataset.dropna()

# Split again

X = dataset[feature_cols]
y = dataset["Target"].astype(int)

In [36]:
# Create TimeSeriesSplit

tscv = TimeSeriesSplit(n_splits=5)

In [37]:
models = {

    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "Decision Tree":
        DecisionTreeClassifier(random_state=42),

    "Random Forest":
        RandomForestClassifier(
            random_state=42,
            n_estimators=100
        )
}

In [38]:
results = []

for model_name, model in models.items():

    accuracy = []
    precision = []
    recall = []
    f1 = []

    for train_index, test_index in tscv.split(X):

        # Split data

        X_train = X.iloc[train_index]
        X_test = X.iloc[test_index]

        y_train = y.iloc[train_index]
        y_test = y.iloc[test_index]



        # Prediction

        prediction = model.predict(X_test)

        # Store metrics

        accuracy.append(
            accuracy_score(y_test, prediction)
        )

        precision.append(
            precision_score(
                y_test,
                prediction,
                zero_division=0
            )
        )

        recall.append(
            recall_score(
                y_test,
                prediction,
                zero_division=0
            )
        )

        f1.append(
            f1_score(
                y_test,
                prediction,
                zero_division=0
            )
        )

    results.append({

        "Model": model_name,

        "Accuracy Mean": np.mean(accuracy),
        "Accuracy Std": np.std(accuracy),

        "Precision Mean": np.mean(precision),
        "Precision Std": np.std(precision),

        "Recall Mean": np.mean(recall),
        "Recall Std": np.std(recall),

        "F1 Mean": np.mean(f1),
        "F1 Std": np.std(f1)

    })

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [11]:
baseline_accuracy = []
baseline_precision = []
baseline_recall = []
baseline_f1 = []

for train_index, test_index in tscv.split(X):

    y_test = y.iloc[test_index]

    # Always predict UP

    baseline_prediction = np.ones(len(y_test), dtype=int)

    baseline_accuracy.append(
        accuracy_score(y_test, baseline_prediction)
    )

    baseline_precision.append(
        precision_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

    baseline_recall.append(
        recall_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

    baseline_f1.append(
        f1_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

results.append({

    "Model":"Naive Baseline",

    "Accuracy Mean":np.mean(baseline_accuracy),
    "Accuracy Std":np.std(baseline_accuracy),

    "Precision Mean":np.mean(baseline_precision),
    "Precision Std":np.std(baseline_precision),

    "Recall Mean":np.mean(baseline_recall),
    "Recall Std":np.std(baseline_recall),

    "F1 Mean":np.mean(baseline_f1),
    "F1 Std":np.std(baseline_f1)

})

In [12]:
baseline_accuracy = []
baseline_precision = []
baseline_recall = []
baseline_f1 = []

for train_index, test_index in tscv.split(X):

    y_test = y.iloc[test_index]

    # Always predict UP

    baseline_prediction = np.ones(len(y_test), dtype=int)

    baseline_accuracy.append(
        accuracy_score(y_test, baseline_prediction)
    )

    baseline_precision.append(
        precision_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

    baseline_recall.append(
        recall_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

    baseline_f1.append(
        f1_score(
            y_test,
            baseline_prediction,
            zero_division=0
        )
    )

results.append({

    "Model":"Naive Baseline",

    "Accuracy Mean":np.mean(baseline_accuracy),
    "Accuracy Std":np.std(baseline_accuracy),

    "Precision Mean":np.mean(baseline_precision),
    "Precision Std":np.std(baseline_precision),

    "Recall Mean":np.mean(baseline_recall),
    "Recall Std":np.std(baseline_recall),

    "F1 Mean":np.mean(baseline_f1),
    "F1 Std":np.std(baseline_f1)

})

In [13]:
results_df = pd.DataFrame(results)

results_df

,Model,Accuracy Mean,Accuracy Std,Precision Mean,Precision Std,Recall Mean,Recall Std,F1 Mean,F1 Std
0,Naive Baseline,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Naive Baseline,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
ranking = results_df.sort_values(
    by="F1 Mean",
    ascending=False
)

ranking

,Model,Accuracy Mean,Accuracy Std,Precision Mean,Precision Std,Recall Mean,Recall Std,F1 Mean,F1 Std
0,Naive Baseline,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Naive Baseline,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
ranking.to_csv(
    "model_ranking.csv",
    index=False
)

print("Evaluation completed successfully.")

Evaluation completed successfully.